[pyprland]
plugins = [
  "scratchpads",
]

[scratchpads.terminal]
command = "alacritty --class alacrittyDropDown -e sh -c 'neofetch; exec $SHELL'"
class = "alacrittyDropDown"
animation = "fromTop"
unfocus = "hide"
size = "65% 65%"

